; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "srvTemp"
#define MyAppVersion "0.4"
#define MyAppPublisher "MAURINSOFT"
#define MyAppURL "http://maurinsoft.com.br"
; O executável instalado é Temperatura.exe (mantido coerente com [Files])
#define MyAppExeName "Temperatura.exe"

[Setup]
; Identificador único da aplicação
AppId={{25E22926-C829-4F42-B173-8912FF91F4D2}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

; Instala em Program Files (auto escolhe x86/x64 adequado)
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename=srvTemp_setup_04
Compression=lzma
SolidCompression=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
UsePreviousAppDir=yes

; Necessário para criar atalho em {commonstartup} e gravar em C:\db
PrivilegesRequired=admin

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Types]
Name: "srvTemp"; Description: {cm:T_srvTemp}

[Components]
Name: "srvTemp"; Description: "Arquivos do srvTemp"; Types: srvTemp;

[CustomMessages]
T_srvTemp=srvTemp
TD_srvTemp=Install demo to srvTemp

[Dirs]
; Cria C:\db com permissão de modificação para usuários e não remove no uninstall
Name: "C:\db"; Permissions: users-modify; Flags: uninsneveruninstall

[Files]
; Executável principal
Source: "D:\projetos\maurinsoft\Temperatura\software\src\Temperatura.exe"; DestDir: "{app}"; Flags: ignoreversion
; Banco de dados: copia para C:\db, não sobrescreve se já existir, e não remove no uninstall
Source: "D:\projetos\maurinsoft\Temperatura\software\db\temperatura.db"; DestDir: "C:\db"; Flags: onlyifdoesntexist uninsneveruninstall ignoreversion

[Icons]
; Menu Iniciar
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
; Área de trabalho (opcional via tarefa)
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
; Iniciar com o Windows (todos os usuários, após login)
Name: "{commonstartup}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
; Executa o app ao final da instalação
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
